package mysql

const (
	MYSQL_DEFAULT_CHARSET string = "utf8mb4"

	MYSQL_READ_USE_TLS  string = "MYSQL_READ_USE_TLS"
	MYSQL_READ_HOST     string = "MYSQL_READ_HOST"
	MYSQL_READ_PORT     string = "MYSQL_READ_PORT"
	MYSQL_READ_USER     string = "MYSQL_READ_USER"
	MYSQL_READ_PASSWORD string = "MYSQL_READ_PASS"
	MYSQL_READ_DATABASE string = "MYSQL_READ_DBNAME"

	MYSQL_WRITE_USE_TLS  string = "MYSQL_WRITE_USE_TLS"
	MYSQL_WRITE_HOST     string = "MYSQL_WRITE_HOST"
	MYSQL_WRITE_PORT     string = "MYSQL_WRITE_PORT"
	MYSQL_WRITE_USER     string = "MYSQL_WRITE_USER"
	MYSQL_WRITE_PASSWORD string = "MYSQL_WRITE_PASS"
	MYSQL_WRITE_DATABASE string = "MYSQL_WRITE_DBNAME"
)
